baseURL = "https://trolloldem.github.io/"
title        = "My Blog"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

pluralizelisttitles = false

copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "A simple personal space about me"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you linke
  enableSharingButtons = true

  # Enable Theme Toggle button
  EnableThemeToggle = true

  # Metadata mostly used in document's head
  description = "Personal page of Gianluca Oldani"
  keywords = "PhD, Security, Databases, Web"
  images = [""]

  # Default theme "light" or "dark"
  defaultTheme = "dark"

[params.footer]
    trademark = 2020
    author = true
    copyright = true 
    rss = true
    topText = ["Powered by <a href=\"http://gohugo.io\">Hugo</a>"]
    bottomText =  ["Hugo <a href=\"https://github.com/rhazdon/hugo-theme-hello-friend-ng\">theme</a> made by <a href=\"https://github.com/rhazdon\">Djordje Atlialp</a>"]


# Social icons
  [[params.SocialIcons]]
    name = "github"
    url = "https://github.com/Trolloldem"

  [[params.SocialIcons]]
      name = "linkedin"
      url = "https://www.linkedin.com/in/gianluca-oldani-632100168/"

  [[params.SocialIcons]]
      name = "stackoverflow"
      url = "https://stackoverflow.com/users/14083453/trolloldem"

[author]
    name = "Gianluca Oldani"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Gianluca Oldani's website"
    subtitle = "A simple personal space about me"
    keywords = ""
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "cd ~"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"

  [[menu.main]]
    identifier  = "teaching"
    name       = "Teachings"
    url        = "teachings/"
  [[menu.main]]
    identifier  = "publications"
    name       = "Publications"
    url        = "publications/"
    [markup]
      [markup.goldmark]
        [markup.goldmark.renderer]
          unsafe = true
